# Update the State of Localization comment by periodically running a python script.

name: Update State of Localization

# Controls when the action will run
on:
  # Action is triggered manually
  workflow_dispatch:

  # Action is runs on push
  push:
    branches:
      - master
  
  # Action runs once a day (in case the mac-mouse-fix-website repo updates, which isn't covered by running on push to mac-mouse-fix repo)
  schedule:  
    - cron: "0 0 * * *" # Minute 0, hour 0, every day. See crontab.guru/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "regenerate-acknowledgements"
  regenerate-state-of-localization:
    
    # Runs on macos runner. That's because we use ibtool from the python script.
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - name: Checkout mac-mouse-fix
      uses: actions/checkout@v4
      with:
        repository: noah-mshank/mac-mouse-fix   # Checkout mmf repo
        ref: master                               # Checkout master branch
        path: './mac-mouse-fix'                   # Place repo at this path relative to $GITHUB_WORKSPACE
        fetch-depth: 0                            # Check out everything
    
    - name: Checkout mac-mouse-fix-website
      uses: actions/checkout@v4
      with:
        repository: noah-mshank/mac-mouse-fix-website # Checkout website repo
        ref: main  
        path: './mac-mouse-fix-website'
        fetch-depth: 0
    
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'   # We developed the script under 3.11
        cache: 'pip'             # caching pip dependencies. This is from the official example. Not totally sure what we're doing here.
        cache-dependency-path: './mac-mouse-fix/Localization/Code/StateOfLocalization/requirements.txt'

    - name: Install python dependencies
      run: |
        python -m pip install -r './mac-mouse-fix/Localization/Code/StateOfLocalization/requirements.txt'
    
    - name: Run script
      working-directory: ./mac-mouse-fix
      run: |
        python ./Localization/Code/StateOfLocalization/script.py --api_key ${{ secrets.GITHUB_TOKEN }}

        
